import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdir, mkdtemp, rm } from 'node:fs/promises';
import { createServer } from 'node:net';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import test from 'node:test';

async function unusedPort(){const server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const {port}=server.address();await new Promise(done=>server.close(done));return port;}

test('auth, roles, user lifecycle, settings persistence and protected API endpoints',async t=>{
  const runtime=await mkdtemp(join(process.cwd(),'.auth-test-')),serverDir=join(runtime,'server'),dataDir=join(runtime,'data');await mkdir(serverDir,{recursive:true});await mkdir(dataDir,{recursive:true});
  const {copyFile}=await import('node:fs/promises');await copyFile(join(process.cwd(),'server/index.js'),join(serverDir,'index.js'));const dbPath=join(dataDir,'kiosco.sqlite');
  const port=await unusedPort(),base=`http://127.0.0.1:${port}/api`,child=spawn(process.execPath,[join(serverDir,'index.js')],{cwd:process.cwd(),env:{...process.env,KIOSCO_PORT:String(port),KIOSCO_DB_PATH:dbPath},stdio:'ignore'});
  t.after(async()=>{if(child.exitCode===null){child.kill();await Promise.race([once(child,'exit'),new Promise(done=>setTimeout(done,1500))]);}await rm(runtime,{recursive:true,force:true});});
  let ready=false;for(let i=0;i<80;i++){try{if((await fetch(`${base}/health`)).ok){ready=true;break}}catch{}await new Promise(done=>setTimeout(done,100));}assert.equal(ready,true);
  const call=async(path,method='GET',body,cookie='')=>{const response=await fetch(`${base}${path}`,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]||''};};
  assert.deepEqual((await call('/auth/status')).data,{setup_required:true});
  assert.equal((await call('/auth/setup','POST',{name:'Admin Principal',email:'admin@kiosco.local',password:'safe-test-password'})).status,201);
  const setup=await call('/auth/setup','POST',{name:'Other Admin',email:'other@kiosco.local',password:'safe-test-password'});assert.equal(setup.status,409);
  const adminLogin=await call('/auth/login','POST',{email:'ADMIN@KIOSCO.LOCAL',password:'safe-test-password'});assert.equal(adminLogin.status,200);const adminCookie=adminLogin.cookie;assert.ok(adminCookie);
  assert.equal((await call('/bootstrap')).status,401,'unauthenticated API must be rejected');
  const boot=await call('/bootstrap','GET',undefined,adminCookie);assert.equal(boot.data.user.role,'admin');
  const product=await call('/products','POST',{name:'Producto permiso',sku:'AUTH-PROD',category_id:boot.data.categories[0].id,stock:3,cost:2,price:5},adminCookie);assert.equal(product.status,201);
  const settings=await call('/settings','GET',undefined,adminCookie);assert.equal(settings.status,200);assert.equal(settings.data.name,'Mi Kiosco');
  assert.equal((await call('/settings','PATCH',{name:'Kiosco Central',expiry_alert_days:14},adminCookie)).data.expiry_alert_days,14);
  assert.equal((await call('/settings','PATCH',{name:'K',expiry_alert_days:0},adminCookie)).status,400);
  const expireSoon=new Date();expireSoon.setUTCDate(expireSoon.getUTCDate()+10);const expiringProduct=await call('/products','POST',{name:'Umbral configurable',sku:'AUTH-EXPIRY',category_id:boot.data.categories[0].id,stock:2,cost:1,price:3,expires_on:expireSoon.toISOString().slice(0,10)},adminCookie);assert.equal(expiringProduct.status,201);
  assert.equal((await call('/products','GET',undefined,adminCookie)).data.find(item=>item.id===expiringProduct.data.id).expiry_status,'expiring');
  await call('/settings','PATCH',{name:'Kiosco Central',expiry_alert_days:5},adminCookie);
  assert.equal((await call('/products','GET',undefined,adminCookie)).data.find(item=>item.id===expiringProduct.data.id).expiry_status,'ok','configured threshold changes server expiry alerts');
  await call('/settings','PATCH',{name:'Kiosco Central',expiry_alert_days:14},adminCookie);
  const newUser=await call('/users','POST',{name:'Empleado Uno',email:'empleado@kiosco.local',password:'employee-test-password',role:'employee'},adminCookie);assert.equal(newUser.status,201);const employeeId=newUser.data.id;
  assert.equal((await call('/users','POST',{name:'Duplicado',email:'EMPLEADO@kiosco.local',password:'employee-test-password',role:'employee'},adminCookie)).status,409);
  const userList=await call('/users','GET',undefined,adminCookie);assert.equal(userList.data.length,2);assert.equal(userList.data.some(user=>'password_hash' in user),false);
  const inspect=new DatabaseSync(dbPath);const stored=inspect.prepare('SELECT password_hash FROM users WHERE id=?').get(employeeId).password_hash;assert.ok(stored&&stored!=='employee-test-password'&&stored.includes(':'));assert.equal(inspect.prepare("SELECT COUNT(*) n FROM admin_audit_log WHERE actor_id=? AND action IN ('user.create','settings.update')").get(boot.data.user.id).n>=2,true);inspect.close();
  const employeeLogin=await call('/auth/login','POST',{email:'empleado@kiosco.local',password:'employee-test-password'});assert.equal(employeeLogin.status,200);const employeeCookie=employeeLogin.cookie;
  assert.equal((await call('/bootstrap','GET',undefined,employeeCookie)).status,200);
  assert.equal((await call('/users','GET',undefined,employeeCookie)).status,403);
  assert.equal((await call('/settings','PATCH',{name:'Hack',expiry_alert_days:1},employeeCookie)).status,403);
  assert.equal((await call('/products','POST',{name:'Hack',sku:'HACK',price:1},employeeCookie)).status,403);
  assert.equal((await call('/purchases','POST',{product_id:product.data.id,quantity:1,unit_cost:2},employeeCookie)).status,403);
  assert.equal((await call('/cash/open','POST',{amount:100},employeeCookie)).status,201,'employee can open the work cash session');
  const sale=await call('/sales','POST',{items:[{id:product.data.id,quantity:1}],payments:[{method:'efectivo',amount:5}]},employeeCookie);assert.equal(sale.status,201,'employee can complete a POS sale');
  assert.equal((await call('/cash','GET',undefined,employeeCookie)).data.expected_cash,105);
  let inspectCash=new DatabaseSync(dbPath);assert.equal(inspectCash.prepare('SELECT user_id FROM cash_movements WHERE sale_id=?').get(sale.data.id).user_id,employeeId);const employeeSession=inspectCash.prepare("SELECT id,opened_by FROM cash_sessions WHERE status='open'").get();assert.equal(employeeSession.opened_by,employeeId);inspectCash.close();
  assert.equal((await call('/cash/close','POST',{counted_cash:105},employeeCookie)).status,200);
  inspectCash=new DatabaseSync(dbPath);assert.equal(inspectCash.prepare('SELECT closed_by FROM cash_sessions WHERE id=?').get(employeeSession.id).closed_by,employeeId);inspectCash.close();
  assert.equal((await call('/products','GET',undefined,employeeCookie)).status,200,'employee can consult stock');
  assert.equal((await call('/users/not-real','PATCH',{name:'x'},employeeCookie)).status,403);
  assert.equal((await call('/users/not-real','PATCH',{name:'x'},adminCookie)).status,404);
  const addedAdmin=await call('/users','POST',{name:'Admin Dos',email:'admin2@kiosco.local',password:'another-safe-password',role:'admin'},adminCookie);assert.equal(addedAdmin.status,201);
  assert.equal((await call(`/users/${addedAdmin.data.id}`,'PATCH',{...addedAdmin.data,active:0},adminCookie)).status,200);
  assert.equal((await call('/users','POST',{name:'Employee 2',email:'empleado2@kiosco.local',password:'employee-test-password',role:'employee'},adminCookie)).status,201);
  const employee2=(await call('/users','GET',undefined,adminCookie)).data.find(user=>user.email==='empleado2@kiosco.local');
  assert.equal((await call(`/users/${employee2.id}`,'PATCH',{...employee2,role:'admin'},adminCookie)).status,200,'admin can change a user role');
  assert.equal((await call(`/users/${employee2.id}`,'PATCH',{...employee2,role:'employee'},adminCookie)).status,200,'admin can restore employee role');
  const self=boot.data.user;
  assert.equal((await call(`/users/${self.id}`,'PATCH',{name:self.name,email:self.email,role:'employee',active:1},adminCookie)).status,409,'last active admin cannot be demoted');
  assert.equal((await call(`/users/${employeeId}`,'PATCH',{name:'Empleado Uno',email:'empleado@kiosco.local',role:'employee',active:0},adminCookie)).status,200);
  assert.equal((await call('/bootstrap','GET',undefined,employeeCookie)).status,401,'deactivation revokes active sessions');
  assert.equal((await call(`/users/${employeeId}`,'PATCH',{name:'Empleado Uno',email:'empleado@kiosco.local',role:'employee',active:1},adminCookie)).status,200,'admin can reactivate a user');
  assert.equal((await call('/auth/login','POST',{email:'empleado@kiosco.local',password:'employee-test-password'})).status,200,'reactivated user can authenticate again');
  assert.equal((await call(`/users/${employeeId}`,'PATCH',{name:'Empleado Uno',email:'empleado@kiosco.local',role:'employee',active:0},adminCookie)).status,200);
  const loggedOut=await call('/auth/logout','POST',{},adminCookie);assert.equal(loggedOut.status,200);assert.equal((await call('/bootstrap','GET',undefined,adminCookie)).status,401);
  assert.equal((await call('/auth/login','POST',{email:'empleado@kiosco.local',password:'employee-test-password'})).status,401);
  const loginAgain=await call('/auth/login','POST',{email:'admin@kiosco.local',password:'safe-test-password'});assert.equal(loginAgain.status,200);
  assert.equal((await call('/settings','GET',undefined,loginAgain.cookie)).data.expiry_alert_days,14,'configuration survives requests and sessions');
  assert.equal((await call('/auth/status')).data.setup_required,false);
});
